version: '3'
services:

  practice-app:
    build: .
    depends_on:
      - db

  db:
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"