version: '3'
services:

  practice-app:
    build: .
    depends_on:
      - practice-db

  practice-db:
    build: ./db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "33060:3306"