name: practice workflow
on: push

jobs:
  build:
    name: Just better action
    runs-on: ubuntu-20.04
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: set up jdk 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Compile with Maven
        run: mvn clean package
      - name: run docker compose
        run: docker compose up --build #--abort-on-container-exit
        
