name: practice workflow
on: push

jobs:
  unitTests:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up jdk 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Unit Tests
        run: mvn -Dtest=personal.priingles.CountryTest test


  build:
    name: Build
    runs-on: ubuntu-20.04
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: set up jdk 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Package and run
        run: |
          mvn package -DskipTests
          docker compose up --build --abort-on-container-exit
      
